Styling
rbd3/bookstore pull request #5
Opened 2023-07-21 17:47 UTC by rbd3

### Change made:
👉 Add Style for all components

2023-07-21 20:22 UTC, VICTOR-CHUKWU requested changes
Hi @rbd3  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 20:22 UTC, VICTOR-CHUKWU commented on src/App.css
> +}
- [ ] This is a style ,milestone so we have to make sure the styling is close to the given design, currently your nav is not aligned to the body of the booklist, kindly make it so
your design :point_down: 
![image](https://github.com/rbd3/bookstore/assets/66097371/1a3b21a4-aaa5-4e55-8806-ae78646b022b)
given design :point_down: 
![image](https://github.com/rbd3/bookstore/assets/66097371/5652e9f8-d24d-4510-b95e-2b0c51e68ba8)

2023-07-21 20:22 UTC, VICTOR-CHUKWU commented on src/App.css
> +}
- [ ] the link texts are not looking like what is on design, kindly fix the font color

2023-07-21 20:22 UTC, VICTOR-CHUKWU commented on src/App.css
> +}
- [ ] kindly adjust the width of this wrapper to look like the given design
your design :point_down: 
![image](https://github.com/rbd3/bookstore/assets/66097371/57c8ed64-451c-4e49-93f6-2def2af3cf49)
given design :point_down: 
![image](https://github.com/rbd3/bookstore/assets/66097371/e43aa713-4eaa-4c1d-ba4a-969cd9f93db8)

2023-07-22 06:44 UTC, tufoinnkuo10 requested changes
Hi @rbd3 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ wireframe well followed

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-07-22 06:44 UTC, tufoinnkuo10 commented on src/App.css
> +.book-title {
- [ ] wonderful job so far. please, like the previous reviewer  noted, this milestone is aimed at our styling looking almost like the zeplin design. Kindly align the book cards with the page title and user logo placeholder like in the original design. 
yours
![Screenshot (1267)_LI](https://github.com/rbd3/bookstore/assets/65298048/e9dfc4f5-d61d-428d-a896-f6c698d46318)
original
![Screenshot (1266)](https://github.com/rbd3/bookstore/assets/65298048/c5d6213f-2d4b-49f4-b28d-2bd153f6a759)

2023-07-22 08:32 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @rbd3 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/2RGhmKXcl0ViM/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 08:40 UTC, merged